### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by LoupCellard** [etalab/cada#17]
Internal Server Error on this URL : https://cada.data.gouv.fr/20182193 related to this : 
"Avis 20182193
 Ministère de l'enseignement supérieur, de la recherche et de l'innovation
Communication par publication du code source de la plateforme Parcoursup".

**Comment by LoupCellard** [comment]
Another internal server error here : http://cada.data.gouv.fr/20182193/

**Comment by taniki** [comment]
C'est bon. Corrigé avec #16 et déployé.

Les deux liens que tu mentionnes fonctionnent
