### ISSUE TITLE
Nom consistant pour les conclusions comportant un slash

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/cada#23]
Bonjour,

Actuellement, les valeurs possibles pour les conclusions sont les suivantes :
- Défavorable/Vie privée
- Favorable
- Favorable / Sauf vie privée
- Favorable/Sauf commercial industriel
- Favorable/Sauf comportement
- Favorable/Sauf vie privée
- Sans objet / Communiqué
- Sans objet / Inexistant
- Sans objet/Communiqué
- Sans objet/Inexistant

Je propose de rassembler les conclusions qui ont un espace avant ou un après le slash. Ceci est fait en supprimant les espaces avant et après le slash séparateur.

J'ai proposé ceci dans la PR #22

**Comment by noirbizarre** [comment]
Fixed by #22
